
services:
  # Servicio del Backend (FastAPI para Stock Flow)
  stockflow-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_stockflow_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - proyecto-net
    volumes:
      - ./backend/app:/app/app

# Red de Comunicación
networks:
  proyecto-net:
    driver: bridge